#!/usr/bin/env bash
echo "Starting setup"

# Check for Homebrew, install if missing
if ! command -v brew &>/dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update

# Install packages
PACKAGES=(
    git
    bat
    macvim
    mysql
    fzf
    ctags
    readline
    python3
)
echo "Installing packages..."
brew install "${PACKAGES[@]}"

echo "Cleaning up..."
brew cleanup

echo "Installing Python packages..."
brew install pipx
pipx install virtualenv
pipx install virtualenvwrapper

# Install cask applications
CASKS=(
    iterm2
    adobe-acrobat-reader
    spotify
    visual-studio-code
    1password
    serial
    google-drive
    nextcloud
    vlc
    raspberry-pi-imager
    brave-browser
)
echo "Installing cask apps..."
for app in "${CASKS[@]}"; do
    brew install --cask "$app"
done

echo "Machine setup completed successfully!"
